-- Cricket Cadets Global - Sample Data Script
-- Execute this script AFTER running supabase-setup.sql to populate with sample data

-- Insert Sample Admin User (password will be: admin123)
-- Note: In production, use proper password hashing
INSERT INTO users (email, password_hash, full_name, role) VALUES 
('admin@cricketcadets.com', '$2b$10$rQZ9QmjKjKjKjKjKjKjKjOeH8H8H8H8H8H8H8H8H8H8H8H8H8H8H8', 'System Administrator', 'super_admin'),
('editor@cricketcadets.com', '$2b$10$rQZ9QmjKjKjKjKjKjKjKjOeH8H8H8H8H8H8H8H8H8H8H8H8H8H8H8', 'Content Editor', 'editor'),
('viewer@cricketcadets.com', '$2b$10$rQZ9QmjKjKjKjKjKjKjKjOeH8H8H8H8H8H8H8H8H8H8H8H8H8H8H8', 'Content Viewer', 'viewer')
ON CONFLICT (email) DO NOTHING;

-- Insert Sample Hero Section for Homepage
INSERT INTO hero_sections (title, subtitle, description, background_image, cta_primary_text, cta_primary_link, cta_secondary_text, cta_secondary_link, badge_text, overlay_opacity, is_active) VALUES 
('Cricket Cadets Global', 'The World''s Premier Cricket Academy', 'Join thousands of young cricketers who have transformed their game with our world-class coaching and proven training methods.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80', 'Start Your Journey', '/programs', 'Watch Our Story', '/about', '🏏 World Class Training', 0.6, true);

-- Insert Sample Programs
INSERT INTO programs (name, slug, subtitle, description, detailed_description, age_group, duration, price, price_period, features, image, icon, color_scheme, is_popular, is_featured, status, category_id) VALUES 
('Junior Cricketers', 'junior-cricketers', 'Perfect for beginners', 'A comprehensive program designed for young cricketers aged 6-10 to learn the fundamentals of cricket in a fun and engaging environment.', 'Our Junior Cricketers program focuses on developing basic cricket skills through fun games and activities. Children will learn proper batting stance, bowling techniques, and fielding positions while building confidence and teamwork skills.', '6-10 years', '8 weeks', 150.00, 'monthly', '["Basic batting techniques", "Bowling fundamentals", "Fielding skills", "Team building activities", "Safety equipment included"]', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80', 'Users', 'from-blue-500 to-purple-600', false, true, 'active', 1),
('Elite Training', 'elite-training', 'Advanced skill development', 'Intensive training program for serious young cricketers looking to take their game to the next level with professional coaching.', 'Our Elite Training program is designed for committed young cricketers who want to excel. With professional coaches, advanced techniques, and competitive match play, this program prepares players for representative cricket.', '12-16 years', '12 weeks', 300.00, 'monthly', '["Professional coaching", "Advanced techniques", "Match simulation", "Video analysis", "Fitness training", "Mental coaching"]', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80', 'Trophy', 'from-green-500 to-blue-600', true, true, 'active', 1),
('Holiday Camps', 'holiday-camps', 'Fun-filled cricket camps', 'Exciting cricket camps during school holidays combining skill development with fun activities and new friendships.', 'Our Holiday Camps offer the perfect blend of cricket training and fun activities. Kids will improve their cricket skills while making new friends and enjoying games, competitions, and special activities.', '8-14 years', '5 days', 200.00, 'per camp', '["Daily cricket training", "Fun games and activities", "New friendships", "Lunch included", "End of camp certificate", "Photo memories"]', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80', 'Target', 'from-orange-500 to-red-600', false, true, 'active', 1);

-- Insert Sample Coaches
INSERT INTO coaches (name, title, achievement, bio, quote, image, specialties, social_links, is_featured, is_active) VALUES 
('Michael Johnson', 'Head Coach & Former International Player', 'Former Australian Test Cricketer with 15 years international experience', 'Michael brings over 20 years of cricket experience to Cricket Cadets Global. Having played 45 Test matches for Australia, he understands what it takes to succeed at the highest level and is passionate about developing the next generation of cricketers.', '"Every great cricketer started with a dream and the right guidance. I''m here to help young players achieve their potential."', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80', '["Batting Technique", "Mental Coaching", "Match Strategy", "Leadership Development"]', '{"twitter": "@mjohnson_coach", "instagram": "@coach_mjohnson", "linkedin": "michael-johnson-cricket"}', true, true),
('Sarah Williams', 'Youth Development Specialist', 'Former Women''s Cricket Captain & Youth Coach of the Year 2023', 'Sarah specializes in youth development and has coached over 500 young cricketers. Her innovative training methods and nurturing approach have helped many players progress to representative levels.', '"Cricket is not just about technique - it''s about building character, confidence, and lifelong friendships."', 'https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80', '["Youth Development", "Bowling Techniques", "Team Building", "Confidence Building"]', '{"twitter": "@sarah_cricket", "instagram": "@sarahwilliams_coach"}', true, true),
('David Chen', 'Technical Skills Coach', 'Level 3 Cricket Australia Coach & Former State Player', 'David focuses on technical skill development and has a keen eye for identifying and correcting technical flaws. His methodical approach has helped hundreds of players improve their game.', '"Perfect practice makes perfect. Every session is an opportunity to get better."', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80', '["Technical Analysis", "Fielding Excellence", "Wicket Keeping", "Video Analysis"]', '{"instagram": "@davidchen_cricket", "linkedin": "david-chen-cricket-coach"}', true, true);

-- Insert Sample Testimonials
INSERT INTO testimonials (name, title, content, rating, image, video_url, location, is_featured, is_video, status) VALUES 
('Emma Thompson', 'Parent of Junior Cricketer', 'My daughter has been with Cricket Cadets Global for 6 months and the improvement in her confidence and skills has been remarkable. The coaches are fantastic and really care about each child''s development.', 5, 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80', NULL, 'Sydney, Australia', true, false, 'published'),
('James Rodriguez', 'Elite Training Graduate', 'The Elite Training program prepared me perfectly for representative cricket. I''m now playing for my state team and it''s all thanks to the amazing coaching at Cricket Cadets Global.', 5, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'Melbourne, Australia', true, true, 'published'),
('Lisa Park', 'Holiday Camp Parent', 'The holiday camps are absolutely fantastic! My son had such a great time and learned so much. He''s already asking when the next camp is. Highly recommended!', 5, 'https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80', NULL, 'Brisbane, Australia', true, false, 'published');

-- Insert Sample Locations
INSERT INTO locations (name, address, city, state, country, postal_code, phone, email, facilities, operating_hours, is_active) VALUES 
('Sydney Cricket Academy', '123 Cricket Street', 'Sydney', 'NSW', 'Australia', '2000', '+61 2 9876 5432', 'sydney@cricketcadets.com', '["Indoor nets", "Outdoor oval", "Video analysis room", "Fitness center", "Cafe"]', '{"monday": "9:00 AM - 8:00 PM", "tuesday": "9:00 AM - 8:00 PM", "wednesday": "9:00 AM - 8:00 PM", "thursday": "9:00 AM - 8:00 PM", "friday": "9:00 AM - 8:00 PM", "saturday": "8:00 AM - 6:00 PM", "sunday": "8:00 AM - 6:00 PM"}', true),
('Melbourne Cricket Center', '456 Sports Avenue', 'Melbourne', 'VIC', 'Australia', '3000', '+61 3 9876 5432', 'melbourne@cricketcadets.com', '["Multiple indoor nets", "Full size oval", "Bowling machine", "Physiotherapy room", "Equipment shop"]', '{"monday": "9:00 AM - 8:00 PM", "tuesday": "9:00 AM - 8:00 PM", "wednesday": "9:00 AM - 8:00 PM", "thursday": "9:00 AM - 8:00 PM", "friday": "9:00 AM - 8:00 PM", "saturday": "8:00 AM - 6:00 PM", "sunday": "8:00 AM - 6:00 PM"}', true);

-- Insert Sample Waitlist Entries
INSERT INTO waitlist (child_name, date_of_birth, gender, phone_number, email, suburb_postcode, cricket_experience, parent_guardian_name, parent_guardian_phone, parent_guardian_email, status, consent_to_contact, consent_to_marketing) VALUES 
('Alex Johnson', '2015-03-15', 'male', '+61 400 123 456', 'alex.johnson@email.com', 'Bondi 2026', 'beginner', 'Mark Johnson', '+61 400 123 456', 'mark.johnson@email.com', 'pending', true, true),
('Sophie Chen', '2013-07-22', 'female', '+61 400 789 012', 'sophie.chen@email.com', 'Richmond 3121', 'club', 'Linda Chen', '+61 400 789 012', 'linda.chen@email.com', 'approved', true, false),
('Ryan Williams', '2014-11-08', 'male', '+61 400 345 678', 'ryan.williams@email.com', 'Surfers Paradise 4217', 'representative', 'Sarah Williams', '+61 400 345 678', 'sarah.williams@email.com', 'contacted', true, true);

-- Insert Sample Blog Posts
INSERT INTO blog_posts (title, slug, excerpt, content, featured_image, status, is_featured, published_at, category_id) VALUES 
('5 Essential Cricket Skills Every Young Player Should Master', '5-essential-cricket-skills', 'Discover the fundamental skills that form the foundation of great cricket players and how to develop them effectively.', 'Cricket is a sport that requires a diverse set of skills, and for young players just starting their journey, it can be overwhelming to know where to focus their efforts. In this comprehensive guide, we''ll explore the five essential cricket skills that every young player should master to build a strong foundation for their cricket career.\n\n## 1. Proper Batting Stance and Grip\n\nThe foundation of good batting starts with the correct stance and grip. A proper stance provides balance and allows for effective shot execution, while the right grip ensures control over the bat.\n\n## 2. Basic Bowling Action\n\nDeveloping a smooth, repeatable bowling action is crucial for accuracy and preventing injury. Young bowlers should focus on a balanced approach and follow-through.\n\n## 3. Fundamental Fielding Positions\n\nUnderstanding where to position yourself in the field and how to move efficiently can make the difference between taking a catch and missing an opportunity.\n\n## 4. Running Between Wickets\n\nSmart running between wickets can turn singles into doubles and help build partnerships. Communication and awareness are key.\n\n## 5. Mental Preparation\n\nCricket is as much a mental game as it is physical. Learning to stay focused and positive under pressure is essential for success.\n\nAt Cricket Cadets Global, we focus on developing all these skills through structured training programs designed specifically for young players.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'published', true, NOW() - INTERVAL '2 days', 2),
('Cricket Cadets Global Wins Youth Development Award', 'cricket-cadets-wins-award', 'We''re proud to announce that Cricket Cadets Global has been recognized for excellence in youth cricket development.', 'We are thrilled to announce that Cricket Cadets Global has been awarded the prestigious Youth Development Excellence Award by the International Cricket Development Council. This recognition highlights our commitment to providing world-class cricket education and development programs for young players.\n\nThe award recognizes organizations that demonstrate exceptional dedication to youth cricket development, innovative training methods, and positive impact on young players'' lives. Our comprehensive approach to cricket education, which combines technical skill development with character building and life skills, has been particularly commended.\n\n"This award is a testament to the hard work and dedication of our entire team," said Michael Johnson, Head Coach at Cricket Cadets Global. "But most importantly, it reflects the amazing progress and achievements of our young cricketers who inspire us every day."\n\nOver the past year, Cricket Cadets Global has:\n- Trained over 1,000 young cricketers\n- Helped 50+ players progress to representative teams\n- Expanded to 5 new locations\n- Launched innovative online training resources\n\nWe want to thank all our players, parents, coaches, and supporters who have made this achievement possible. This award motivates us to continue raising the bar in youth cricket development.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'published', true, NOW() - INTERVAL '1 week', 2);

-- Success message
SELECT 'Sample data inserted successfully! Your database is now populated with test data.' as status;